apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cloud-api
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: cloud-api-placement
        requeueAfterSeconds: 180
  template:
    metadata:
      name: cloud-api-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/PacktPublishing/Openshift-Multi-Cluster-management.git
        targetRevision: main
        path: sample-go-app/clouds-api/k8s/
      destination:
        namespace: cloud-api
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=orphan
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: cloud-api-placement
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - dev
