apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: quarkus-quickstarts-appset
  namespace: openshift-gitops
spec:
  generators:
    - clusterDecisionResource:
        configMapRef: acm-placement
        labelSelector:
          matchLabels:
            cluster.open-cluster-management.io/placement: prod-clusters
        requeueAfterSeconds: 180
  template:
    metadata:
      name: quarkus-quickstart-{{name}}
      labels:
        velero.io/exclude-from-backup: "true"
    spec:
      project: default
      source:
        repoURL: https://github.com/PacktPublishing/Openshift-Multi-Cluster-management.git
        targetRevision: main
        path: quarkus-getting-started/k8s/overlay/v2/
      destination:
        namespace: chap14-review-cicd
        server: "{{server}}"
      syncPolicy:
        automated:
          selfHeal: false
          prune: true
        syncOptions:
          - CreateNamespace=true
          - PrunePropagationPolicy=orphan
---
apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  name: prod-clusters
  namespace: openshift-gitops
spec:
  predicates:
    - requiredClusterSelector:
        labelSelector:
          matchExpressions:
            - key: env
              operator: In
              values:
                - prod
