apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: pipelines-appset-clusterrole
rules:
- apiGroups:
  - argoproj.io
  resources:
  - applicationsets
  verbs:
  - patch
  - get
  - create
- apiGroups:
  - cluster.open-cluster-management.io
  resources:
  - placements
  verbs:
  - patch
  - get
  - create
    