apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  creationTimestamp: null
  name: pipelines-cicd-appset-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: pipelines-appset-clusterrole
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: chap14-review-cicd
