apiVersion: v1 
baseDomain: hybridcloud.com 
controlPlane: 
  hyperthreading: Enabled 
  name: master 
  platform: 
  gcp: 
    type: n2-standard-4 
    zones: 
    - us-central1-a 
    - us-central1-c 
  osDisk: 
    diskType: pd-ssd 
    diskSizeGB: 1024 
    encryptionKey: 
      kmsKey: 
      name: worker-key 
      keyRing: test-machine-keys 
      location: global 
      projectID: project-id 
  replicas: 3 
compute: 
- hyperthreading: Enabled 
  name: worker 
  platform: 
  gcp: 
    type: n2-standard-4 
    zones: 
    - us-central1-a 
    - us-central1-c 
    osDisk: 
    diskType: pd-standard 
    diskSizeGB: 128 
    encryptionKey: 
    kmsKey: 
      name: worker-key 
      keyRing: test-machine-keys 
      location: global 
      projectID: project-id 
  replicas: 3 
metadata: 
name: test-cluster 
networking: 
  clusterNetwork: 
  - cidr: 10.128.0.0/14 
    hostPrefix: 23 
  machineNetwork: 
  - cidr: 10.0.0.0/16 
  networkType: OpenShiftSDN 
  serviceNetwork: 
  - 172.30.0.0/16 
platform: 
gcp: 
  projectID: openshift-production 
  region: us-central1 
pullSecret: '{"auths": ...}' 
fips: false 
sshKey: ssh-ed25519 AAAA... 